import styled from "styled-components";

import { GiReturnArrow } from "react-icons/gi";
import { MdKeyboardArrowRight, MdKeyboardArrowDown } from "react-icons/md";

import { useState } from "react";

export const HomeCode = ({ handlePage }) => {
  const icons = ["{", "}", "=>", "(", ")", "[", "]", "<>", "</>", "<", ">", "</", "/>"];

  const [exportToggle, exportToggleSet] = useState(true);
  const handleExport = () => exportToggleSet((previousState) => !previousState);

  const [returnToggle, returnToggleSet] = useState(true);
  const handleReturn = () => returnToggleSet((previousState) => !previousState);

  const [const1, const1Set] = useState(true);
  const handleConst1 = () => const1Set((previousState) => !previousState);

  const [const2, const2Set] = useState(true);
  const handleConst2 = () => const2Set((previousState) => !previousState);

  return (
    <Container>
      <section>
        <Number>1</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <White>styled</White>
            <Pink>from</Pink>
            <Yellow>
              "styled-components"{" "}
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>2</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>useState</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "react"{" "}
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>3</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>NavLink</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "react-router-dom"{" "}
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>4</Number>
        <br />
      </section>
      <section>
        <Number>5</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>BsFileEarmarkCode</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "react-icons/bs"{" "}
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>6</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>MdDoubleArrow</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "react-icons/md"{" "}
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>7</Number>
        <br />
      </section>
      <section>
        <Number>8</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>Title</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "<strong>..</strong>/layout/Title"
            </Yellow>
            <White>
              <Strong>
                <Strong>;</Strong>
              </Strong>
            </White>
          </div>
        </Content>
      </section>
      <section>
        <Number>9</Number>
        <Content>
          <div>
            <Pink>import</Pink>
            <Yellow>{icons[0]}</Yellow>
            <White>HomeCode</White>
            <Yellow>{icons[1]}</Yellow>
            <Pink>from</Pink>
            <Yellow>
              "<strong>.</strong>/HomeCode"
            </Yellow>
            <White>
              <Strong>;</Strong>
            </White>
          </div>
        </Content>
      </section>
      <section>
        <Number>10</Number>
        <br />
      </section>
      <section>
        <Number>11</Number>
        <Content>
          <div>
            {exportToggle ? <MdKeyboardArrowDown onClick={handleExport} role="button" /> : <MdKeyboardArrowRight style={{ opacity: 1 }} onClick={handleExport} role="button" />}
            <Pink>export</Pink>
            <Pink>const</Pink>
            <Green>About</Green>
            <Pink> = </Pink>
            <Orange>{icons[3]}</Orange>
            <Orange>{icons[4]}</Orange>
            <Pink>{icons[2]}</Pink>
            <Yellow>{icons[0]}</Yellow>
          </div>
        </Content>
      </section>
      {exportToggle && (
        <>
          <section>
            <Number>12</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Pink>const</Pink>
                  <Blue>{icons[5]}</Blue>
                  <Purple>
                    page<White>,</White>
                  </Purple>
                  <Green>pageSet</Green>
                  <Blue>{icons[6]}</Blue>
                  <Pink> = </Pink>
                  <Green>
                    useState<Yellow>{icons[3]}</Yellow>
                  </Green>
                  <Purple>true</Purple>
                  <Yellow>{icons[4]}</Yellow>
                  <White>
                    <Strong>;</Strong>
                  </White>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>13</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Pink>const</Pink>
                  <Green>handlePage</Green>
                  <Pink> = </Pink>
                  <Orange>{icons[3]}</Orange>
                  <Orange>{icons[4]}</Orange>
                  <Pink>{icons[2]}</Pink>
                  <Green>
                    pageSet
                    <Orange>
                      {icons[3]}
                      <Red>
                        {icons[3]}
                        <Orange>
                          <i>previousState</i>
                        </Orange>
                        <Red>{icons[4]}</Red>
                      </Red>
                    </Orange>
                  </Green>
                  <Pink>{icons[2]}</Pink>
                  <Orange>
                    <Pink>!</Pink>
                    <i>previousState</i>
                    <Orange>{icons[4]}</Orange>
                  </Orange>
                  <White>
                    <Strong>;</Strong>
                  </White>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>14</Number>
            <BorderLeft>
              <br />
            </BorderLeft>
          </section>
          <section>
            <Number>15</Number>
            <Content>
              <BorderLeft>
                <div>
                  {!returnToggle && <MdKeyboardArrowRight style={{ opacity: 1 }} onClick={handleReturn} />}
                  {returnToggle && <MdKeyboardArrowDown onClick={handleReturn} />}
                  <Pink>return</Pink>
                  <Orange>{icons[3]}</Orange>
                </div>
              </BorderLeft>
            </Content>
          </section>
          {returnToggle && (
            <>
              <section>
                <Number>16</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <div>
                        <White>{icons[7]}</White>
                      </div>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>17</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <div>
                          <Orange>{icons[0]}</Orange>
                          <Purple>page</Purple>
                          <Pink>?</Pink>
                          <Red>{icons[3]}</Red>
                        </div>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>18</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <div>
                            <White>
                              {icons[9]}
                              <Blue>
                                <i>Container</i>
                              </Blue>
                              <White>{icons[10]}</White>
                            </White>
                          </div>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>19</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Blue>
                                  <i>Title </i>
                                </Blue>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>20</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <div>
                                <White>
                                  {icons[9]}
                                  <Pink>h1</Pink>
                                  <White>{icons[10]}</White>
                                </White>
                                <White>Sobre</White>
                                <White>
                                  {icons[11]}
                                  <Pink>
                                    h1<White>{icons[10]}</White>
                                  </Pink>
                                </White>
                              </div>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>21</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Blue>
                                  <i>Title </i>
                                </Blue>
                                <White>{icons[12]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>22</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                              <White>
                                Rodrigo Liberti, 31 anos - Curitiba/Pr<Strong>.</Strong>
                              </White>
                              <White>
                                {icons[11]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>23</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                              <White>
                                Desenvolvedor Front-End trabalho com ReactJs, atualmente estudando Laravel para me tornar um desenvolvedor Fullstack<Strong>.</Strong>
                              </White>
                              <White>
                                {icons[11]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>24</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                              <White>
                                Experiência como desenvolvedor ReactJs 1+ Trabalhei com portais web aonde realizei um clone do Trello<Strong>.</Strong>
                              </White>
                              <White>
                                {icons[11]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>25</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>26</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <White>Reconhecido por colegas como um profissional com um grande potencial, dedicação e com entregas de qualidade e pontuais,</White>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>27</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <White>
                                sempre disposto a ajudar os colegas e em constante busca por conhecimento<Strong>.</Strong>
                              </White>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>28</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[11]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>29</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>p</Pink>
                                {icons[10]}
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>30</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <White>
                                Cursando desde 2021 {icons[9]}
                                <Pink>b</Pink>
                                {icons[10]} Análise e Desenvolvimento de Sistemas {icons[11]}
                                <Pink>b</Pink>
                                {icons[10]} A onde estou no quarto período<Strong>.</Strong>
                              </White>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>31</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[11]}
                                <Pink>p</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>32</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>div</Pink>
                                <White>{icons[10]}</White>
                              </White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>33</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <div>
                                <White>
                                  {icons[9]}
                                  <Blue>
                                    <i>CodeButton</i>
                                  </Blue>
                                </White>
                                <Green>
                                  <i>onClick</i>
                                  <Pink>=</Pink>
                                  <Brown>
                                    {icons[0]}
                                    <Green>handlePage</Green>
                                    <Brown>{icons[1]}</Brown>
                                  </Brown>
                                </Green>
                                <Green>
                                  <i>role</i>
                                  <Pink>=</Pink>
                                  <Yellow>"button"</Yellow>
                                  <White>{icons[10]}</White>
                                </Green>
                              </div>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>34</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <div>
                                  <White>
                                    {icons[9]}
                                    <Blue>
                                      <i>BsFileEarmarkCode</i>
                                    </Blue>
                                  </White>
                                  <White>{icons[12]}</White>
                                </div>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>35</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <White>
                                  Ver código fonte<strong>...</strong>
                                </White>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>36</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <div>
                                <White>{icons[11]}</White>
                                <Blue>
                                  <i>CodeButton</i>
                                  <White>{icons[10]}</White>
                                </Blue>
                              </div>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>37</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <div>
                                <White>
                                  {icons[9]}
                                  <Blue>
                                    <i>CodeButton</i>
                                  </Blue>
                                </White>
                              </div>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>38</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <div>
                                  <White>
                                    {icons[9]}
                                    <Blue>
                                      <i>NavLink</i>
                                    </Blue>
                                  </White>
                                  <Green>
                                    <i>to</i>
                                    <Pink>=</Pink>
                                    <Yellow>"/projetos"</Yellow>
                                    <White>{icons[10]}</White>
                                  </Green>
                                </div>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>39</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <BorderLeft>
                                  <div>
                                    <White>
                                      {icons[9]}
                                      <Blue>
                                        <i>MdDoubleArrow</i>
                                      </Blue>
                                    </White>
                                    <White>{icons[12]}</White>
                                  </div>
                                </BorderLeft>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>40</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <BorderLeft>
                                  <White>
                                    Meus Projetos<strong>...</strong>
                                  </White>
                                </BorderLeft>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>41</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <BorderLeft>
                                <div>
                                  <White>{icons[11]}</White>
                                  <Blue>
                                    <i>NavLink</i>
                                    <White>{icons[10]}</White>
                                  </Blue>
                                </div>
                              </BorderLeft>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>42</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <BorderLeft>
                              <div>
                                <White>{icons[11]}</White>
                                <Blue>
                                  <i>CodeButton</i>
                                  <White>{icons[10]}</White>
                                </Blue>
                              </div>
                            </BorderLeft>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>43</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <BorderLeft>
                            <div>
                              <White>
                                {icons[9]}
                                <Pink>div</Pink>
                              </White>
                              <White>{icons[12]}</White>
                            </div>
                          </BorderLeft>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>44</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <div>
                            <White>{icons[11]}</White>
                            <Blue>
                              <i>Container</i>
                              <White>{icons[10]}</White>
                            </Blue>
                          </div>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>45</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <div>
                          <Red>{icons[4]}</Red>
                          <White>:</White>
                          <Red>{icons[3]}</Red>
                        </div>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>46</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <BorderLeft>
                          <div>
                            <White>
                              {icons[9]}
                              <Blue>
                                <i>HomeCode</i>
                              </Blue>
                            </White>
                            <Green>
                              <i>handlePage</i>
                              <Pink>=</Pink>
                              <Brown>{icons[0]}</Brown>
                              <Green>handlePage</Green>
                              <Brown>{icons[1]}</Brown>
                            </Green>
                            <Green>
                              <i>role</i>
                              <Pink>=</Pink>
                              <Yellow>"button"</Yellow>
                              <White>{icons[10]}</White>
                            </Green>
                            <White>{icons[12]}</White>
                          </div>
                        </BorderLeft>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>47</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <BorderLeft>
                        <div>
                          <Red>{icons[4]}</Red>
                          <Yellow>{icons[1]}</Yellow>
                        </div>
                      </BorderLeft>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
              <section>
                <Number>48</Number>
                <Content>
                  <BorderLeft>
                    <BorderLeft>
                      <div>
                        <White>{icons[8]}</White>
                      </div>
                    </BorderLeft>
                  </BorderLeft>
                </Content>
              </section>
            </>
          )}
          <section>
            <Number>49</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Orange>{icons[4]}</Orange>
                  <White>;</White>
                </div>
              </BorderLeft>
            </Content>
          </section>
        </>
      )}
      <section>
        <Number>50</Number>
        <Content>
          <div>
            <Yellow>{icons[1]}</Yellow>
            <White>;</White>
          </div>
        </Content>
      </section>
      <section>
        <Number>51</Number>
        <Content>
          <div>
            <br />
          </div>
        </Content>
      </section>
      {/* sdgs */}
      <section>
        <Number>52</Number>
        <Content>
          <div>
            {const1 ? <MdKeyboardArrowDown onClick={handleConst1} role="button" /> : <MdKeyboardArrowRight style={{ opacity: 1 }} onClick={handleConst1} role="button" />}
            <Pink>Const</Pink>
            <Purple>Container</Purple>
            <Pink>=</Pink>
            <Purple>
              Styled
              <White>
                <strong>.</strong>div
              </White>
              <Yellow>`</Yellow>
            </Purple>
          </div>
        </Content>
      </section>
      {const1 && (
        <>
          <section>
            <Number>53</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    display
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    flex
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>54</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    flex-direction
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    column
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>55</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    align-items
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    center
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>56</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    padding
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>0</Purple>
                  <Purple>
                    20
                    <Pink>
                      px
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Pink>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>57</Number>
            <Content>
              <BorderLeft>
                <br />
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>58</Number>
            <Content>
              <BorderLeft>
                <div>
                  {icons[10]}
                  <Pink>div</Pink>
                  <Yellow>{icons[0]}</Yellow>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>59</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    display
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    flex
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>60</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    gap
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    20<Pink>px</Pink>
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>61</Number>
            <Content>
              <BorderLeft>
                <Yellow>{icons[1]}</Yellow>
              </BorderLeft>
            </Content>
          </section>
          <section>
            
          </section>
          <br />
          <br />
          <br />
          <section>
            <Number>49</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    height
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Blue>
                    calc<Yellow>{icons[3]}</Yellow>
                    <Purple>
                      100<Pink>vh</Pink>
                    </Purple>
                  </Blue>
                  <Pink> - </Pink>
                  <Purple>
                    90<Pink>px</Pink>
                    <Yellow>{icons[4]}</Yellow>
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>51</Number>
            <Content>
              <BorderLeft>
                <Pink>@media</Pink>
                <Purple>screen</Purple>
                <Pink>and</Pink>
                <Yellow>
                  {icons[3]}
                  <Blue>
                    max-width
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                </Yellow>
                <Purple>
                  648
                  <Pink>
                    px<Yellow>{icons[4]}</Yellow>
                  </Pink>
                </Purple>
                <White>{icons[0]}</White>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>52</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    display
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    flex
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>53</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    flex-direction
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    column
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>54</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    justify-content
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    space-arround
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>55</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Blue>
                    overflow
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    auto
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>56</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <br />
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>57</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  {icons[10]}
                  <Pink>img</Pink>
                  <Yellow>{icons[0]}</Yellow>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>58</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <BorderLeft>
                    <Blue>
                      width
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      300<Pink>px</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </BorderLeft>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>59</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <BorderLeft>
                    <Blue>
                      height
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      300<Pink>px</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </BorderLeft>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>60</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Yellow>{icons[1]}</Yellow>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>61</Number>
            <Content>
              <BorderLeft>{icons[1]}</BorderLeft>
            </Content>
          </section>
        </>
      )}
      <section>
        <Number>62</Number>
        <Content>
          <div>
            <Yellow>
              `
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>63</Number>
        <Content>
          <br />
        </Content>
      </section>
      <section>
        <Number>64</Number>
        <Content>
          <div>
            {!const2 && <MdKeyboardArrowRight style={{ opacity: 1 }} onClick={handleConst2} role="button" />}
            {const2 && <MdKeyboardArrowDown onClick={handleConst2} role="button" />}
            <Pink>Const</Pink>
            <Purple>Content</Purple>
            <Pink>=</Pink>
            <Purple>
              Styled
              <White>
                <strong>.</strong>span
              </White>
              <Yellow>`</Yellow>
            </Purple>
          </div>
        </Content>
      </section>
      {const2 && (
        <>
          <section>
            <Number>65</Number>
            <Content>
              <BorderLeft>
                <div>
                  <Blue>
                    padding
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                  <Purple>
                    50<Pink>px</Pink>
                    <White>
                      <Strong>;</Strong>
                    </White>
                  </Purple>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>66</Number>
            <Content>
              <BorderLeft>
                <br />
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>67</Number>
            <Content>
              <BorderLeft>
                <div>
                  <White>{icons[10]}</White>
                  <Pink>p</Pink>
                  <Yellow>{icons[0]}</Yellow>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>68</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      font-size
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      16<Pink>px</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>69</Number>
            <Content>
              <BorderLeft>
                <Yellow>{icons[1]}</Yellow>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>70</Number>
            <Content>
              <BorderLeft>
                <br />
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>71</Number>
            <Content>
              <BorderLeft>
                <div>
                  <White>{icons[10]}</White>
                  <Pink>div</Pink>
                  <Yellow>{icons[0]}</Yellow>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>72</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      display
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      flex
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>73</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      flex-wrap
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      flex
                      <White>;</White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>74</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      alingn-items
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      center
                      <White>
                        <Strong>
                          <Strong>;</Strong>
                        </Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>75</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      justify-content
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      center
                      <White>
                        <Strong>
                          <Strong>;</Strong>
                        </Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>76</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      gap
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      20<Pink>px</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>77</Number>
            <Content>
              <BorderLeft>
                <Yellow>{icons[1]}</Yellow>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>78</Number>
            <Content>
              <BorderLeft>
                <br />
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>79</Number>
            <Content>
              <BorderLeft>
                <div>
                  <White>{icons[10]}</White>
                  <Pink>h1</Pink>
                  <Yellow>{icons[0]}</Yellow>
                </div>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>80</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      font-size
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      2.5<Pink>rem</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>81</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      margin-bottom
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      10<Pink>px</Pink>
                      <White>
                        <Strong>;</Strong>
                      </White>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>82</Number>
            <Content>
              <BorderLeft>
                <Yellow>{icons[1]}</Yellow>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>83</Number>
            <Content>
              <BorderLeft>
                <Yellow>
                  <br />
                </Yellow>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>84</Number>
            <Content>
              <BorderLeft>
                <Pink>@media</Pink>
                <Purple>screen</Purple>
                <Pink>and</Pink>
                <Yellow>
                  {icons[3]}
                  <Blue>
                    max-width
                    <Pink>
                      <Strong>:</Strong>
                    </Pink>
                  </Blue>
                </Yellow>
                <Purple>
                  648
                  <Pink>
                    px<Yellow>{icons[4]}</Yellow>
                  </Pink>
                </Purple>
                <White>{icons[0]}</White>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>85</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <Blue>
                      padding
                      <Pink>
                        <Strong>:</Strong>
                      </Pink>
                    </Blue>
                    <Purple>
                      30
                      <Pink>
                        px
                        <White>
                          <Strong>;</Strong>
                        </White>
                      </Pink>
                    </Purple>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>86</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <br />
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>87</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <div>
                    <White>{icons[10]}</White>
                    <Pink>h1</Pink>
                    <Yellow>{icons[0]}</Yellow>
                  </div>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>88</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <BorderLeft>
                    <div>
                      <Blue>
                        font-size
                        <Pink>
                          <Strong>:</Strong>
                        </Pink>
                      </Blue>
                      <Purple>
                        2<Pink>rem</Pink>
                        <White>
                          <Strong>;</Strong>
                        </White>
                      </Purple>
                    </div>
                  </BorderLeft>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>89</Number>
            <Content>
              <BorderLeft>
                <BorderLeft>
                  <Yellow>{icons[1]}</Yellow>
                </BorderLeft>
              </BorderLeft>
            </Content>
          </section>
          <section>
            <Number>90</Number>
            <Content>
              <BorderLeft>
                <Yellow>{icons[1]}</Yellow>
              </BorderLeft>
            </Content>
          </section>
        </>
      )}
      <section>
        <Number>91</Number>
        <Content>
          <div>
            <Yellow>
              `
              <White>
                <Strong>;</Strong>
              </White>
            </Yellow>
          </div>
        </Content>
      </section>
      <section>
        <Number>92</Number>
        <Content>
          <br />
        </Content>
      </section>
      <CodeButton onClick={handlePage}>
        <GiReturnArrow />
        Voltar a Home...
      </CodeButton>
    </Container>
  );
};

const Container = styled.div`
  height: calc(100vh - 90px);
  overflow: auto;
  padding: 0 30px;

  section {
    display: grid;
    grid-template-columns: 40px auto;
  }

  @media screen and (max-width: 648px) {
    padding: 5px 10px 15px;
    font-size: 12px;

    section {
      grid-template-columns: 40px auto;
      width: calc(100vw - 110px);
      white-space: nowrap;
    }
  }
`;

const Number = styled.div`
  padding-right: 25px;
  color: #5f43a1;
  display: flex;
  align-items: flex-end;
  flex-direction: column;

  @media screen and (max-width: 648px) {
    padding-left: 10px;
  }
`;

const Content = styled.div`
  position: relative;

  div {
    display: flex;
    align-items: center;
    gap: 5px;

    svg {
      position: absolute;
      left: -20px;
      font-size: 20px;
      opacity: 0.4;

      :hover {
        opacity: 1;
      }
    }
  }
  @media screen and (max-width: 648px) {
    padding-right: 20px;
  }
`;

const BorderLeft = styled.div`
  border-left: 1px solid #7774746f;
  padding-left: 15px;
`;

const CodeButton = styled.div`
  position: fixed;
  top: 100px;
  right: 40px;
  width: 200px;
  padding: 10px 20px;
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
  border-radius: 10px;
  border: 1px solid #191d20;
  background-color: #1f2428;
  transition: 0.3s;

  :hover {
    background-color: #1f242870;
  }

  @media screen and (max-width: 648px) {
    top: 90vh;
    right: 12px;
    width: 150px;
  }
`;

const Pink = styled.span`
  color: #ff79c6;
`;

const White = styled.span`
  color: #fff;
`;

const Yellow = styled.span`
  color: #f1fa8c;
`;

const Green = styled.span`
  color: #50fa7b;
`;

const Orange = styled.span`
  color: #ffb86c;
`;

const Brown = styled.span`
  color: #996328;
`;

const Blue = styled.span`
  color: #8be9fd;
`;

const Purple = styled.span`
  color: #bd93f9;
`;

const Red = styled.span`
  color: red;
`;

const Strong = styled.strong`
  margin-left: 2px;
`;
